# render.yaml
services:
  - type: web
    name: multiverse-server
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash deploy.sh"  # ← Usa el script
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.4"
      - key: SECRET_KEY
        sync: false
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
      - key: MERCADOPAGO_WEBHOOK_SECRET
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
    healthCheckPath: /healthz