# alembic/versions/612c2e47671f_add_mp_subscription_id_to_subscription.py
"""add mp_subscription_id to subscription

Revision ID: 612c2e47671f
Revises: 5d2717278e2d
Create Date: 2025-04-05 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

revision = '612c2e47671f'
down_revision = '5d2717278e2d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mp_subscription_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_subscriptions_mp_subscription_id'), ['mp_subscription_id'])

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_subscriptions_mp_subscription_id'), type_='unique')
        batch_op.drop_column('mp_subscription_id')

    # ### end Alembic commands ###